# Run tests
test:
    pytest -vv -s src/tests

# Lint code with ruff
lint:
    ruff format .
    ruff check . --fix
    mypy .  

# Build the project
build:
    hatch build

# Run Helios Server
run:
    python src/helios/main.py

# Run Helios Server in debug mode
run-debug:
    python src/helios/helios.py --debug

# Check logs
logs:
    tail -f logs/helios.log

# check status of the Server
status:
    curl http://localhost:5000/status

# Run all checks (linting, formatting check, type checking, and tests)
check:
    @echo "Checking code style..."
    just format --check
    @echo "Linting..."
    just lint
    @echo "Checking types..."
    just type-check
    @echo "Running tests..."
    just test

# Install dependencies
install:
    pip install -e .

# Pre-commit hooks setup
pre-commit-setup:
    pre-commit install

# Run pre-commit on all files
pre-commit-run:
    pre-commit run --all-files

# Update requirements.txt 
update-reqs:
    #!/usr/bin/env bash
    pip-compile pyproject.toml --output-file=requirements.txt

# sync envs
sync:
    hatch env prune
    hatch env create
    just update-reqs

# Alias for convenience
t: test
l: lint
c: check
i: install
s: sync

